version: '2'

services:

    em:
        image: trzeci/emscripten-slim:sdk-tag-1.38.8-64bit
        #build: ./docker/em/
        volumes:
            - ./src:/src
        command: bash -c "emcc core.cpp -s WASM=1 -s USE_SDL=2 -O3 -o index.js"

    server:
        build: ./docker/server/
        volumes:
            - ./src:/src
        ports:
            - "80:80"
